/**
 * NexusOS — Intent Router (Multi-Persona Hub)
 * 
 * Central routing layer to select the correct persona (Student | Founder | Developer).
 */

import { parseStudentIntent } from './intent/studentIntentParser.js';
import { mapIntentToTasks as mapStudentTasks } from './intent/studentTaskMapper.js';
import { formatStudentOutput } from './formatters/studentFormatter.js';

import { parseFounderIntent } from './intent/founderIntentParser.js';
import { mapFounderIntentToTasks } from './mappers/founderTaskMapper.js';
import { formatFounderOutput } from './formatters/founderFormatter.js';

import { parseDeveloperIntent } from './intent/developerIntentParser.js';
import { mapDeveloperIntentToTasks } from './mappers/developerTaskMapper.js';
import { formatDeveloperOutput } from './formatters/developerFormatter.js';

import { universalPlanner } from './core/universalPlanner.js';

import type { TaskNode, TaskDAG } from '@nexus-os/types';

export type OSMode = 'student' | 'founder' | 'developer';
export type ArchitectureMode = 'legacy' | 'os';

export interface RoutedIntent {
  intent: any;
  tasks: TaskNode[];
  formatter: (synthesis: any) => any;
  dag?: TaskDAG; // NEW: The DAG generated by the OS-first planner
}

/**
 * NexusOS — Intent Router (Multi-Persona Hub)
 * 
 * Central routing layer to select the correct persona (Student | Founder | Developer).
 * Now supports "OS Mode" for primitive-first planning.
 */
export async function routeIntent(
  input: string, 
  mode: OSMode, 
  archMode: ArchitectureMode = 'legacy'
): Promise<RoutedIntent> {
  console.log(`[IntentRouter] 🗺️ Routing mission via ${mode.toUpperCase()} mode (Arch: ${archMode.toUpperCase()}).`);

  // 1. OS Mode: Use the universal planner (Primitive-first)
  if (archMode === 'os') {
    const dag = await universalPlanner.plan(input);
    return {
      intent: { type: 'universal', goal: input },
      tasks: dag.nodes,
      formatter: (s) => s, // Generic formatter for OS mode
      dag
    };
  }

  // 2. Legacy Mode: Keep current persona-based logic
  switch (mode) {
    case 'founder': {
      const intent = parseFounderIntent(input);
      const tasks = mapFounderIntentToTasks(intent);
      return { intent, tasks, formatter: formatFounderOutput };
    }

    case 'developer': {
      const intent = parseDeveloperIntent(input);
      const tasks = mapDeveloperIntentToTasks(intent);
      return { intent, tasks, formatter: formatDeveloperOutput };
    }

    case 'student':
    default: {
      const intent = parseStudentIntent(input);
      const tasks = mapStudentTasks(intent);
      return { intent, tasks, formatter: formatStudentOutput };
    }
  }
}
